### ISSUE TITLE
Rever Pequenos Detalhes de Polimeno da Interface

### ISSUE THREAD

**Issue by luana2fernandes** [RomuloPBenedetti/Simanihot#11]
- [x] Em dados meteorológicos 1 colocar dois eixos: em um deles a unidade é ºC e no outro é MJ/m² dia. Retirar g/m2.
- [x] Nos modelos de balanço hidrico, os dados de solo da aba classificação do solo, onde tem acentuação no nome do solo, sai errada a acentuação.
![image](https://cloud.githubusercontent.com/assets/12518142/7739077/3957dd1a-ff32-11e4-9876-13f6618e60c8.png)
- [x] Na última versão do Simanihot, retirar o future conversor. Ele não precisa ser disponivel para os usuários.
- [x] No help do SimalArroz, fala algo sobre exportação dos dados para excel, e em um botão para isso. Isso está ativo no Simanihot? 
- [x] Com relação ao conversor normal (não o future) seria possível escolher o local onde o arquivo de saída irá ser alocado?

-[ ] Na versão para o usuário, zerar latitudes, e também dados de solo no modelo de Ritchie. Deixar 400 ppm de CO2 como padrão, 12500 pl/ha de densidade. Zerar datas de plantio e colheita.

**Comment by RomuloPBenedetti** [comment]
É preciso decidir o que será feito com o Future Conversor, o que podemos resolver na próxima reunião, data do atual Milestone **0.6.2**

**Comment by RomuloPBenedetti** [comment]
> Nos modelos de balanço hidrico, os dados de solo da aba classificação do solo, onde tem acentuação no nome do solo, sai errada a acentuação. 

Este bug está contemplado no ticket #7 .

> Com relação ao conversor normal (não o future) seria possível escolher o local onde o arquivo de saída irá ser alocado?

Este bug está contemplado no ticket #9, seria bom dar sujestões das melhorias de interface de conversor por la nos comentários.
