### ISSUE TITLE
Detalhes para rever na interface

### ISSUE THREAD

**Issue by luana2fernandes** [RomuloPBenedetti/Simanihot#14]
- [x] zerar latitude
- [x] ~~Definir o numero de camadas máxima como 10.~~
- [x] A legenda do gráfico conteúdo de água e FATS quando rodado com o modelo de Ritchie, precisa estar detalhado na legenda à direita (com aqueles vistos) cada uma das camadas: SW(1) =  conteúdo de água atual da camada 1; SW(2) =  conteúdo de água atual da camada 2; e assim por diante quantas tiverem; e delimitar no gráfico o mínimo e o máximo valor de conteúdo de água, para eles sempre variarem entre 0,05 e 0,46.
![imagem 4](https://cloud.githubusercontent.com/assets/12518142/7950845/9882969c-0976-11e5-88c2-3ccb99c2a324.png)
- [x] remover macro da interface

**Comment by RomuloPBenedetti** [comment]
número de camadas é uma definição de exceptions, abrir uma nova issue com exceptions do balanço hídrico

**Comment by RomuloPBenedetti** [comment]
Considerando que será necessário de qualquer forma editar a localidade melhor iniciar com o primeiro município da lista selecionado.
