### ISSUE TITLE
Problemas ao inserir dados meteorologicos

### ISSUE THREAD

**Issue by amanda-thirza** [RomuloPBenedetti/Simanihot#31]
Baixei os dados do INMET, colei no bloco de notas. Entretanto quando fui converter não funcionou, só apareceu a seguinte mensagem: Cabeçalho incompativel, valores não batem com os usados pelo programa.

**Comment by RomuloPBenedetti** [comment]
Existe um espaço na coluna produzida pelo INMET que precisa ser removido, é um espaço gerado pelo proprio site do INMET,

**Comment by amanda-thirza** [comment]
Mesmo retirando o espaço eu não estou conseguindo... Coloco o arquivo para converter e não aparece nada, simplesmente NADA. Então tento inserir e o programa não aceita.

**Comment by RomuloPBenedetti** [comment]
por favor use essa ferramenta para compartilhar comigo seu arquivo de texto:
https://gist.github.com/

**Comment by amanda-thirza** [comment]
https://gist.github.com/amanda-thirza/0324f62d03c96323af2a#file-gistfile1-txt

**Comment by amanda-thirza** [comment]
https://gist.github.com/amanda-thirza/0324f62d03c96323af2a#file-gistfile1-txt

**Comment by amanda-thirza** [comment]
https://gist.github.com/amanda-thirza/9699a573412960193154#file-dados-de-sm-26-09-a-26-11

**Comment by RomuloPBenedetti** [comment]
Parece que o instalador possui uma versão antiga do conversor, está faltando calculo do **latgraus** que inclusive está com uma variável diferente (WHAT) da atual no repositório: https://github.com/RomuloPBenedetti/Simanihot/blob/master/Simanihot_GUI/src/processors/ConversorProcessor.java#L238
